AWSTemplateFormatVersion: '2010-09-09'

Description: 'IAM ROLE AND USER CREATION'

Parameters:
  Password:
    NoEcho: 'false'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters

Resources:
  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: AdminUser
      LoginProfile:
        Password: !Ref 'Password'

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: UserA
      LoginProfile:
        Password: !Ref 'Password'
      Policies: # list of inline policy documents that are embedded in the user
        - PolicyName: inlineS3ReadOnlyPolicy # give a unique name to this policy
          PolicyDocument: # JSON policy document
            Version: '2012-10-17'
            Statement: # allow read only access to all S3 buckets
              - Effect: Allow
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - !Ref 'myCustomerManagedPolicyForEC2'

  myCustomerManagedPolicyForEC2:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: customerManagedEC2ReadOnlyPolicy # give a name to this policy
      Description: Customer managed policy for read only access to EC2 instance
      Path: '/'
      PolicyDocument: # (required) JSON policy document 
        Version: '2012-10-17'
        Statement: # allow read only access to EC2 instance
          - Effect: Allow
            Action: 'ec2:Describe'
            Resource: '*'

  UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: UserGroup

  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AdminGroup

  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'UserGroup'
      Users: [!Ref 'User']

  Admins:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'AdminGroup'
      Users: [!Ref 'AdminUser']

  UserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudFormationReadOnly
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['cloudformation:Describe*', 'cloudformation:List*', 'cloudformation:Get*']
          Resource: '*'
      Groups: [!Ref 'UserGroup']
  
  AdminPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudFormationAdmin
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: cloudformation:*
          Resource: '*'
      Groups: [!Ref 'AdminGroup']

  IAMRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: SSM_Role_For_EC2
      Description: SSM role for EC2 Servers
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      MaxSessionDuration: 3600

  MFAdevice:
    Type: AWS::IAM::VirtualMFADevice
    Properties: 
      Path: '/'
      Users: 
        - !Ref AdminUser
      VirtualMfaDeviceName: 'MFA_device_for_admin'

  Keys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'AdminUser'

Outputs:
  AccessKey:
    Value: !Ref 'Keys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [Keys, SecretAccessKey]
    Description: AWSSecretAccessKey of new user